In [24]:
import torch
import torchvision
import torchvision.transforms as transforms

In [25]:
trainset = torchvision.datasets.MNIST(root="./data", train=True, download=True)

In [26]:
type(trainset)

torchvision.datasets.mnist.MNIST

In [27]:
trainset

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train

In [28]:
trainset.data[0]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

In [29]:
transform = transforms.Compose([
    transforms.ToTensor(),
])

trainset= torchvision.datasets.MNIST(root="./data", train=True, transform=transform)

In [30]:
trainset

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
           )

In [31]:
trainset.data.shape

torch.Size([60000, 28, 28])

In [32]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5), (0.5)) 
])

trainset= torchvision.datasets.MNIST(root="./data", train=True, transform=transform)

In [33]:
trainset

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=0.5, std=0.5)
           )

In [34]:
trainloader = torch.utils.data.DataLoader(
    dataset=trainset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

trainloader

In [38]:
images, labels = next(iter(trainloader))

In [39]:
images.shape

torch.Size([32, 1, 28, 28])

In [ ]:
trainset = torchvision.datasets.CIFAR10(root="./data", train=True, download=True)

In [43]:
print([0, 1])

[0, 1]


In [45]:
len(trainloader)

1875

In [48]:
testset = torchvision.datasets.MNIST(root="./data", train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, 32, shuffle=False)

In [50]:
images, labels = next(iter(testloader))

In [51]:
labels.data

tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5,
        4, 0, 7, 4, 0, 1, 3, 1])

In [53]:
labels

tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5,
        4, 0, 7, 4, 0, 1, 3, 1])